// utils/sampleData.ts
import type { SpreadsheetData } from "../types";

export const createSampleSpreadsheetData = (): SpreadsheetData => {
  return {
    A1: {
      id: "A1",
      rawValue: "Product",
      computedValue: "Product",
      displayValue: "Product",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#f3f4f6",
        horizontalAlign: "left",
        verticalAlign: "top",
        bold: true,
      },
    },
    B1: {
      id: "B1",
      rawValue: "Quantity",
      computedValue: "Quantity",
      displayValue: "Quantity",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#f3f4f6",
        horizontalAlign: "left",
        verticalAlign: "top",
        bold: true,
      },
    },
    C1: {
      id: "C1",
      rawValue: "Price",
      computedValue: "Price",
      displayValue: "Price",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#f3f4f6",
        horizontalAlign: "left",
        verticalAlign: "top",
        bold: true,
      },
    },
    D1: {
      id: "D1",
      rawValue: "Total",
      computedValue: "Total",
      displayValue: "Total",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#f3f4f6",
        horizontalAlign: "left",
        verticalAlign: "top",
        bold: true,
      },
    },
    A2: {
      id: "A2",
      rawValue: "Apples",
      computedValue: "Apples",
      displayValue: "Apples",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    B2: {
      id: "B2",
      rawValue: "10",
      computedValue: "10",
      displayValue: "10",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    C2: {
      id: "C2",
      rawValue: "1.50",
      computedValue: "1.50",
      displayValue: "1.50",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    D2: {
      id: "D2",
      rawValue: "=B2*C2",
      computedValue: 15,
      displayValue: "15",
      type: "formula",
      formula: "=B2*C2",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    A3: {
      id: "A3",
      rawValue: "Bananas",
      computedValue: "Bananas",
      displayValue: "Bananas",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    B3: {
      id: "B3",
      rawValue: "5",
      computedValue: "5",
      displayValue: "5",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    C3: {
      id: "C3",
      rawValue: "0.80",
      computedValue: "0.80",
      displayValue: "0.80",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    D3: {
      id: "D3",
      rawValue: "=B3*C3",
      computedValue: 4,
      displayValue: "4",
      type: "formula",
      formula: "=B3*C3",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
      },
    },
    A5: {
      id: "A5",
      rawValue: "Grand Total",
      computedValue: "Grand Total",
      displayValue: "Grand Total",
      type: "text",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#ffffff",
        horizontalAlign: "left",
        verticalAlign: "top",
        bold: true,
      },
    },
    D5: {
      id: "D5",
      rawValue: "=SUM(D2:D3)",
      computedValue: 19,
      displayValue: "19",
      type: "formula",
      formula: "=SUM(D2:D3)",
      style: {
        fontSize: 14,
        textColor: "#000000",
        backgroundColor: "#e5f3ff",
        horizontalAlign: "left",
        verticalAlign: "top",
        bold: true,
      },
    },
  };
};
